# Runtime Image
FROM tensorflow/tensorflow:2.13.0-gpu-jupyter

RUN apt-get update && apt-get install -y \
        ffmpeg \
        libgstreamer1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-good1.0-dev \
        graphviz \
        git \
        cmake \
        libsm6 \
        libxext6 \
        libxrender-dev \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        python3-numpy \
        gcc \
        build-essential \
        gfortran \
        wget \
        curl \
        graphicsmagick \
        libgraphicsmagick1-dev \
        libatlas-base-dev \
        libavcodec-dev \
        libavformat-dev \
        libgtk2.0-dev \
        libjpeg-dev \
        liblapack-dev \
        libswscale-dev \
        pkg-config \
        software-properties-common \
        zip && \
        rm -rf /var/lib/apt/lists/* && \
        apt-get purge   --auto-remove && \
        apt-get clean

RUN python3 -m pip install --no-cache --upgrade pip dlib face_recognition jupyterlab

WORKDIR /home/jupyter

COPY requirements.txt /home/jupyter/


RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--port=5555","--allow-root"]
