# Runtime Image
FROM tensorflow/tensorflow:2.14.0rc1-gpu-jupyter

RUN apt-get update && apt-get install -y \
        ffmpeg \
        libgstreamer1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-good1.0-dev \
        graphviz \
        git \
        cmake \
        libsm6 \
        libxext6 \
        libxrender-dev \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        python3-numpy \
        gcc \
        build-essential \
        gfortran \
        wget \
        curl \
        graphicsmagick \
        libgraphicsmagick1-dev \
        libatlas-base-dev \
        libavcodec-dev \
        libavformat-dev \
        libgtk2.0-dev \
        libjpeg-dev \
        liblapack-dev \
        libswscale-dev \
        pkg-config \
        software-properties-common \
        zip && \
        rm -rf /var/lib/apt/lists/* && \
        apt-get purge   --auto-remove && \
        apt-get clean

# --no-cache-dir is returning the following error for some packages: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
RUN python3 -m pip install --upgrade pip dlib face_recognition jupyterlab

RUN curl -fsSL https://code-server.dev/install.sh | sh

WORKDIR /home/jupyter

COPY requirements.txt /home/jupyter/

RUN pip install -r requirements.txt

# ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--port=5555","--allow-root"]
ENTRYPOINT ["code-server"]
